### ISSUE TITLE
Doesn't work with recent django versions (>0.96.2)

### ISSUE THREAD

**Issue by ghost** [django-mptt/django-mptt#54]
Originally [GC 30](http://code.google.com/p/django-mptt/issues/detail?id=30)

<b>What steps will reproduce the problem?</b>
1. After Signal refactoring - http://code.djangoproject.com/wiki/
BackwardsIncompatibleChanges#Signalrefactoring, mptt seems broken

You will get the below error
dispatcher.connect(pre_save, signal=model_signals.pre_save, sender=model)
AttributeError: 'module' object has no attribute 'connect'

<b>What is the expected output? What do you see instead?</b>

It should work.

<b>What version of the product are you using? On what operating system?</b>
0.2.1

<b>Please provide any additional information below.</b>

Have fixed this issue. Please use the attached patch file.
