### ISSUE TITLE
TreeManyToManyField and add_related_count

### ISSUE THREAD

**Issue by gandalfar** [django-mptt/django-mptt#390]
When upgrading from Django 1.6.5 and django_mptt 0.6.0 to Django 1.8.3 and django_mptt 0.7.4, the following case with TreeManyToManyField breaks:

I have two models:

```
class MerlotCategory(MPTTModel):
    name = models.CharField(max_length=150)
    merlot_id = models.IntegerField()
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['name']

    def __unicode__(self):
        return self.name

class Course(models.Model):
    ..
    merlot_categories = TreeManyToManyField('MerlotCategory', blank=True)
    ..
```

The following query used to work:

```
MerlotCategory.objects.add_related_count(
        MerlotCategory.objects.root_nodes(), Course, 'id', 'merlot_categories', True
)

 [<MerlotCategory: Academic Support Services>, <MerlotCategory: Arts>, <MerlotCategory: Business>, <MerlotCategory: Education>, <MerlotCategory: Humanities>, <MerlotCategory: Mathematics and Statistics>, <MerlotCategory: Science and Technology>, <MerlotCategory: Social Sciences>, <MerlotCategory: Workforce Development>]

```

but now returns an error:

```
In [2]: MerlotCategory.objects.add_related_count(
   ...:         MerlotCategory.objects.root_nodes(), Course, 'id', 'merlot_categories', True
   ...: )
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-8ef672b78e8f> in <module>()
      1 MerlotCategory.objects.add_related_count(
----> 2         MerlotCategory.objects.root_nodes(), Course, 'id', 'merlot_categories', True
      3 )

/home/gandalf/ocwc_search/eggs/django_mptt-0.7.4-py2.7.egg/mptt/managers.pyc in add_related_count(self, queryset, rel_model, rel_field, count_attr, cumulative)
    464                     'mptt_fk': qn(rel_model._meta.get_field(rel_field).column),
    465                     'mptt_table': qn(self.tree_model._meta.db_table),
--> 466                     'mptt_rel_to': qn(mptt_field.rel.field_name),
    467                     'tree_id': qn(meta.get_field(self.tree_id_attr).column),
    468                     'left': qn(meta.get_field(self.left_attr).column),

AttributeError: 'NoneType' object has no attribute 'field_name'
```

I have no idea what's wrong or how to debug this. `mptt_field` is `<django.db.models.fields.AutoField: id>` and `rel` is `None`.

**Comment by gandalfar** [comment]
Ok, so I found a way to fix it, but still seems like a change in behaviour that can be documented:

Based on documentation, the command that returns correct result can be written as:
```
MerlotCategory.objects.add_related_count(
        MerlotCategory.objects.root_nodes(), Course, 'merlot_categories', 'o_count', cumulative=True
)
```

Which works in 0.7.4, but doesn't in 0.6.0. But it works correctly.

**Comment by matthiask** [comment]
This references Django 1.6 / django-mptt 0.6, both long past end-of-life. If still reproducible on a supported version please open a new issue. See #833.
