### ISSUE TITLE
No release of MPTT works with current release of django

### ISSUE THREAD

**Issue by ghost** [django-mptt/django-mptt#74]
Originally [GC 51](http://code.google.com/p/django-mptt/issues/detail?id=51)

<b>What steps will reproduce the problem?</b>
1. Install django 1.0.2
2. Install django-mptt 0.2.1
3. Define trivial MPTT model

class Property(models.Model):
  name = models.CharField(max_length=50)
  parent = models.ForeignKey('self', null=True, blank=True,
related_name='dependent_properties')

mptt.register(Property, order_insertion_by=['name'])

Run syncdb

<b>What is the expected output? What do you see instead?</b>
Expect to create appropriate tables.

Fails to create tables. Traceback:

Traceback (most recent call last):
  File
&quot;/usr/local/lib/python2.5/site-packages/django/core/management/commands/runserver.py&quot;,
line 48, in inner_run
    self.validate(display_num_errors=True)
  File
&quot;/usr/local/lib/python2.5/site-packages/django/core/management/base.py&quot;,
line 246, in validate
    num_errors = get_validation_errors(s, app)
  File
&quot;/usr/local/lib/python2.5/site-packages/django/core/management/validation.py&quot;,
line 28, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File
&quot;/usr/local/lib/python2.5/site-packages/django/db/models/loading.py&quot;, line
128, in get_app_errors
    self._populate()
  File
&quot;/usr/local/lib/python2.5/site-packages/django/db/models/loading.py&quot;, line
57, in _populate
    self.load_app(app_name, True)
  File
&quot;/usr/local/lib/python2.5/site-packages/django/db/models/loading.py&quot;, line
72, in load_app
    mod = __import__(app_name, {}, {}, ['models'])
  File &quot;/data2/development/mptt/mptt_test/../mptt_test/attrs/models.py&quot;,
line 8, in &lt;module&gt;
    mptt.register(Property, order_insertion_by=['name'])
  File &quot;/home/tom/lib/python2.5/site-packages/mptt/**init**.py&quot;, line 73,
in register
    dispatcher.connect(pre_save, signal=model_signals.pre_save, sender=model)
AttributeError: 'module' object has no attribute 'connect'

<b>What version of the product are you using? On what operating system?</b>
0.2.1 / FreeBSD 7

<b>Please provide any additional information below.</b>

This was resolved by issue 36 last November in trunk, but there is still no
release which works with django 1.0.2, and the last release was 17 months
ago - is this project abandonware?
