### ISSUE TITLE
MPTT 0.7.x breaks django manager method from_queryset()

### ISSUE THREAD

**Issue by fritz-k** [django-mptt/django-mptt#378]
In version 0.6.x it was possible to add custom QuerySets to the mptt model via

    class MyModel(MPTTModel):
        ...
        objects = mptt.managers.TreeManager.from_queryset(MyQuerySet)() 

After upgrading to 0.7.3, I get the error `'TreeQuerySet' object has no attribute 'my_query'`.

Looks like commit 2bbd90ee834e0d3bd5772330194d9bdd8b184b63 broke django's `from_queryset()` by returning a new QuerySet.

**Comment by craigds** [comment]
Interesting. I haven't seen `from_queryset` before

**Comment by craigds** [comment]
Please test this fix and provide feedback. Cheers :)

**Comment by fritz-k** [comment]
Works like a charm, thanks for the quick fix!
Cheers :)
